version: '4.29'

services:
  postgres-nest:
    image: postgres:16.2
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres-nest-data:/var/lib/postgresql/data/

  todolist_nest:
    build:
      dockerfile: Dockerfile
      context: './todolist_nest'
    restart: unless-stopped
    ports:
      - '3000:3000'
    # environment:
    # POSTGRES_HOST: localhost
    # POSTGRES_PORT: 5432
    # POSTGRES_USER: ${DB_USER}
    # POSTGRES_PASSWORD: ${DB_PASSWORD}
    # POSTGRES_DB: ${DB_NAME}
    depends_on:
      - postgres-nest
    volumes:
      - ./todolist_nest:/app

  vue-project:
    build:
      dockerfile: Dockerfile
      context: './vue-project'
    restart: unless-stopped
    ports:
      - '8080:8080'
    depends_on:
      - todolist_nest
    volumes:
      - ./vue-project:/app

  # react-app:
  #   build:
  #     dockerfile: Dockerfile
  #     context: './react-app'
  #   restart: unless-stopped
  #   ports:
  #     - '8000:8000'
  #   depends_on:
  #     - todolist_nest
  #   volumes:
  #     - ./react-app:/app

volumes:
  postgres-nest-data:
